version: "3.9"

services:

  backend:
    build:
      context: ./new_ai_agent
    container_name: ai_backend
    ports:
      - "8000:8000"
    env_file:
      - ./new_ai_agent/.env

  frontend:
    build:
      context: ./frontend
    container_name: ai_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend